title: Gender Trends
description: > # this means to ignore newlines until "baseurl:"
  Gender Trends is a networked index of the documents and media that inform research, treatment, policy and education concerning gender non-conforming children and adolescents.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://citemaps.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings  
author: Gender Trends # add your name
author-img: bird.jpg # add your photo
about-author: citation guide # add description
social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: citemaps # add your Github handle
# social-linkedin: # add your Linkedin handle
social-email: submissions@citemaps.ch # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 3
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
