title: Cite Maps
description: > # this means to ignore newlines until "baseurl:"
 public interest citation networks
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://citemaps.github.io/gender-trends" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
# Author Settings
author: cite maps # add your name
author-img: bird.jpg # add your photo
about-author: "<small style=\"background-color:DodgerBlue;\">citation networks<br />informing<br />public interests</small>"
social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: citemaps # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: "submissions@citemaps.ch" # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 3
paginate_path: "/page/:num"
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
